name: build

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up container using docker compose
        run: docker-compose up -d
      - name: Run build
        run: docker-compose exec -it preview bundle exec middleman build
